[package]
authors = ["David Spies <dnspies@gmail.com>"]
edition = "2018"
name = "standing-relations"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"

[dev-dependencies]
goldenfile = "1.1"
